services:
  node-device-guard:
    build: .
    container_name: node-device-guard
    restart: unless-stopped
    network_mode: host # нужен для conntrack (доступ к conntrack на хосте)
    cap_add:
      - NET_ADMIN # требуется для conntrack
    env_file:
      - .env
